In [1]:
print 'hello world'

hello world


In [2]:
'helloworld'

'helloworld'

In [4]:
print 'hi'

hi


! header

% header

# Header

In [5]:
(190**4 - 120/0.3)*1780

2319713088000.0

In [6]:
import numpy

In [7]:
import scipy

In [8]:
import pandas

In [9]:
import matplotlib

# Машинное обучение и анализ данных
## Математика и Python
Задание 1

import numpy

In [10]:
import numpy

In [11]:
numpy.__version__

'1.14.3'

In [12]:
import scipy

In [13]:
scipy.__version__

'1.1.0'

In [14]:
import pandas

In [15]:
pandas.__version__

u'0.23.0'

In [16]:
import matplotlib

In [17]:
matplotlib.__version__

'2.2.2'

In [24]:
print " ".join([str(x ** 2 % 2) for x in range(4)])

0 1 0 1


In [26]:
import pandas as pd

In [27]:
frame = pd.DataFrame({'numbers':range(10), 'chars':['a'] * 10})

In [28]:
frame

chars  numbers
0     a        0
1     a        1
2     a        2
3     a        3
4     a        4
5     a        5
6     a        6
7     a        7
8     a        8
9     a        9

In [29]:
new_line = {'chars':'b', 'numbers':'10'}

In [30]:
frame.append(new_line)

TypeError: Can only append a Series if ignore_index=True or if the Series has a name

In [31]:
frame_2 = pd.read_csv('_62e88c592115ea3459114560893e5ef6_dataset.tsv', sep = '\t', header = 0)

In [32]:
frame_2

Name       Birth       City  Position
0      Иванов А.А.  22.03.1980     Москва       NaN
1     Сорокин И.В.  07.08.1965  Волгоград   инженер
2       Белов М.М.  13.02.1980     Ростов  менеджер
3  Мельникова Д.С.  15.04.1985     Ростов       NaN
4      Рыбина Е.П.  19.11.1985     Москва   инженер
5     Костров С.О.  31.05.1985     Москва    стажер

In [34]:
frame_2.dtypes

Name        object
Birth       object
City        object
Position    object
dtype: object

In [37]:
frame_2.Birth = frame_2.Birth.apply(pd.to_datetime)

In [38]:
frame_2

Name      Birth       City  Position
0      Иванов А.А. 1980-03-22     Москва       NaN
1     Сорокин И.В. 1965-07-08  Волгоград   инженер
2       Белов М.М. 1980-02-13     Ростов  менеджер
3  Мельникова Д.С. 1985-04-15     Ростов       NaN
4      Рыбина Е.П. 1985-11-19     Москва   инженер
5     Костров С.О. 1985-05-31     Москва    стажер

In [39]:
frame_2.dtypes

Name                object
Birth       datetime64[ns]
City                object
Position            object
dtype: object

In [40]:
frame_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
Name        6 non-null object
Birth       6 non-null datetime64[ns]
City        6 non-null object
Position    4 non-null object
dtypes: datetime64[ns](1), object(3)
memory usage: 264.0+ bytes


In [41]:
frame_2.fillna('разнорабочий', inplace = True)

In [42]:
frame_2

Name      Birth       City      Position
0      Иванов А.А. 1980-03-22     Москва  разнорабочий
1     Сорокин И.В. 1965-07-08  Волгоград       инженер
2       Белов М.М. 1980-02-13     Ростов      менеджер
3  Мельникова Д.С. 1985-04-15     Ростов  разнорабочий
4      Рыбина Е.П. 1985-11-19     Москва       инженер
5     Костров С.О. 1985-05-31     Москва        стажер

In [44]:
frame_2.Position

0    разнорабочий
1         инженер
2        менеджер
3    разнорабочий
4         инженер
5          стажер
Name: Position, dtype: object

In [45]:
frame_2[['Position']]

Position
0  разнорабочий
1       инженер
2      менеджер
3  разнорабочий
4       инженер
5        стажер

In [46]:
frame_2[['Name', 'Position']]

Name      Position
0      Иванов А.А.  разнорабочий
1     Сорокин И.В.       инженер
2       Белов М.М.      менеджер
3  Мельникова Д.С.  разнорабочий
4      Рыбина Е.П.       инженер
5     Костров С.О.        стажер

In [48]:
frame_2.head(3)

Name      Birth       City      Position
0   Иванов А.А. 1980-03-22     Москва  разнорабочий
1  Сорокин И.В. 1965-07-08  Волгоград       инженер
2    Белов М.М. 1980-02-13     Ростов      менеджер

In [49]:
frame_2[:3]

Name      Birth       City      Position
0   Иванов А.А. 1980-03-22     Москва  разнорабочий
1  Сорокин И.В. 1965-07-08  Волгоград       инженер
2    Белов М.М. 1980-02-13     Ростов      менеджер

In [50]:
frame_2[-3:]

Name      Birth    City      Position
3  Мельникова Д.С. 1985-04-15  Ростов  разнорабочий
4      Рыбина Е.П. 1985-11-19  Москва       инженер
5     Костров С.О. 1985-05-31  Москва        стажер

In [51]:
frame_2.loc[[1,3,5], ['Name', 'City']]

Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [52]:
frame_2.iloc[[1,3,5], [0,2]]

Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [54]:
frame_2.ix[[1,3,5], ['Name', 'City']]

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [55]:
frame_2.ix[[1,3,5],[0,2]]

/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


Name       City
1     Сорокин И.В.  Волгоград
3  Мельникова Д.С.     Ростов
5     Костров С.О.     Москва

In [57]:
frame_2[frame_2.Birth >= pd.datetime(1985,1,1)]

Name      Birth    City      Position
3  Мельникова Д.С. 1985-04-15  Ростов  разнорабочий
4      Рыбина Е.П. 1985-11-19  Москва       инженер
5     Костров С.О. 1985-05-31  Москва        стажер

In [58]:
frame_2[(frame_2.Birth >= pd.datetime(1985,1,1)) & (frame_2.City != 'Москва')]

Name      Birth    City      Position
3  Мельникова Д.С. 1985-04-15  Ростов  разнорабочий

In [59]:
frame_2[(frame_2.Birth >= pd.datetime(1985,1,1)) | (frame_2.City == 'Волгоград')]

Name      Birth       City      Position
1     Сорокин И.В. 1965-07-08  Волгоград       инженер
3  Мельникова Д.С. 1985-04-15     Ростов  разнорабочий
4      Рыбина Е.П. 1985-11-19     Москва       инженер
5     Костров С.О. 1985-05-31     Москва        стажер

In [61]:
frame_2.shape

(6, 4)

In [70]:
frame_2['IsStudent'] = (False, True)

ValueError: Length of values does not match length of index

In [71]:
import numpy as np

In [72]:
x = [2, 3, 4, 6]
y = np.array(x)

In [73]:
print type(x), x
print type(y), y

<type 'list'> [2, 3, 4, 6]
<type 'numpy.ndarray'> [2 3 4 6]


In [74]:
print x[1:3]

[3, 4]


In [75]:
print y[1:3]

[3 4]


In [76]:
print x[[0, 2]]

TypeError: list indices must be integers, not list

In [77]:
print y[[0, 2]]

[2 4]


In [78]:
print y[y > 3]

[4 6]


In [79]:
print x * 5


[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [80]:
print y * 5

[10 15 20 30]


In [81]:
print x ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [82]:
print y ** 2

[ 4  9 16 36]


In [83]:
matrix = [[1,2,4], [3,1,0]]

In [84]:
nd_array = np.array(matrix)

In [85]:
print matrix[1][2]

0


In [87]:
print nd_array[1,2]

0


In [88]:
print np.random.rand()

0.577828134892


In [89]:
print np.random.randn()

-1.01098279319


In [90]:
print np.random.randn(4)

[-0.82334352  1.14987857  0.53393778 -0.80565954]


In [91]:
print np.random.randn(4, 5)

[[-0.24301776  1.8499466   0.15408338 -1.67624704 -0.08192388]
 [ 2.62526891 -0.73906618 -0.71126325 -1.32743377 -0.76660908]
 [ 0.48011848  0.32823723  0.41200019  1.58430906  2.13448093]
 [-0.73677686 -0.18970089  0.55190706  0.75186087 -0.30759346]]


In [92]:
print np.arange(0, 8, 0.1)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5
 3.6 3.7 3.8 3.9 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3
 5.4 5.5 5.6 5.7 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1
 7.2 7.3 7.4 7.5 7.6 7.7 7.8 7.9]


In [93]:
print range(0, 8, 0.1)

TypeError: range() integer step argument expected, got float.

In [94]:
%timeit np.arange(0, 10000)
%timeit range(0, 10000)

The slowest run took 9.86 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.47 µs per loop
10000 loops, best of 3: 64.6 µs per loop


In [95]:
from scipy import optimize

In [96]:
def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

print f([3.2, 0.1])

3.0


In [97]:
x_min = optimize.minimize(f, [5, 5])
print x_min

      fun: 3.0000000000011435
 hess_inv: array([[ 0.94055055, -0.16183475],
       [-0.16183475,  0.55944947]])
      jac: array([-2.05636024e-06,  5.36441803e-07])
  message: 'Optimization terminated successfully.'
     nfev: 16
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([3.19999896, 0.10000026])


In [98]:
print x_min.x

[3.19999896 0.10000026]


In [99]:
from scipy import linalg

In [100]:
a = np.array([[3,2,0], [1,-1,0], [0,5,1]])
b = np.array([2,4,-1])
x = linalg.solve(a, b)
print x

[ 2. -2.  9.]


In [101]:
print np.dot(a, x)

[ 2.  4. -1.]


In [102]:
numpy.random.rand(4, 5)

array([[0.68918949, 0.46658132, 0.89644979, 0.94569815, 0.35760178],
       [0.65491111, 0.81722325, 0.13559903, 0.88831985, 0.46692524],
       [0.34646574, 0.13924696, 0.77277465, 0.62018954, 0.32533606],
       [0.89890579, 0.12023505, 0.38881984, 0.75710252, 0.23357502]])

In [103]:
a = numpy.array([6, 3, -5]) 

In [104]:
b = numpy.array([-1, 0, 7])

In [106]:
import scipy

In [109]:
from scipy import spatial

In [111]:
scipy.spatial.distance.cdist(a[:, numpy.newaxis], b[:, numpy.newaxis], metric='euclidean')

array([[ 7.,  6.,  1.],
       [ 4.,  3.,  4.],
       [ 4.,  5., 12.]])

In [112]:
scipy.spatial.distance.cdist(b, a, metric='euclidean')




ValueError: XA must be a 2-dimensional array.

In [113]:
scipy.spatial.distance.cdist(a[numpy.newaxis, :], b[numpy.newaxis, :], metric='euclidean')

array([[14.2126704]])

In [114]:
numpy.linalg.norm(a, ord=2) - np.linalg.norm(b, ord=2)

1.2955324534752801

In [115]:
a = numpy.array([0, -1, 11])

In [116]:
b = numpy.array([3, 7, 2])

In [117]:
a * b

array([ 0, -7, 22])

In [118]:
b.dot(a)

15

In [119]:
numpy.dot(a, b) / numpy.linalg.norm(a) / numpy.linalg.norm(b)

0.1724707686818527

In [120]:
numpy.dot(a, b)

15

In [121]:
a = numpy.array([8, 10, -1, 0, 0])

In [122]:
a = a.reshape((1, 5))

In [123]:
a

array([[ 8, 10, -1,  0,  0]])

In [124]:
a = a[:, numpy.newaxis]

In [125]:
a

array([[[ 8, 10, -1,  0,  0]]])

In [126]:
a = a.reshape((5, 1))

In [127]:
a

array([[ 8],
       [10],
       [-1],
       [ 0],
       [ 0]])

In [128]:
a = a[numpy.newaxis, :]

In [129]:
a

array([[[ 8],
        [10],
        [-1],
        [ 0],
        [ 0]]])

In [130]:
e = np.arange(1, 13, 2).reshape((3, 2))

In [131]:
e

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [132]:
a = np.array([4, 3, 2], [2, 9, 1], [3, 1, 9])

ValueError: only 2 non-keyword arguments accepted

In [133]:
b = np.eye(2, 3)

In [134]:
b

array([[1., 0., 0.],
       [0., 1., 0.]])

In [135]:
d = np.ones((10, 10))

In [136]:
d

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [139]:
a = np.eye(4, 5)

In [140]:
a[[0, 3], [1, 3]]

array([0., 1.])